test042b8:
  cloudfront_service_exists: false
  dggr_acm_certificate_arn: arn:aws:acm:us-east-1:739940681129:certificate/20be5ea8-0082-4346-90be-9890f94f10a0
  dggr_acm_certificate_arn_virginia: arn:aws:acm:us-east-1:739940681129:certificate/20be5ea8-0082-4346-90be-9890f94f10a0
  dggr_hostname: dggr.app
  dggr_zone_id: Z01023802GBWXW1MRJGTO
  eks_service_exists: false
  fargate_service_exists: true
  lambda_service_exists: false
  use_dggr_domain: true
