produb6a51:
  cloudfront_service_exists: false
  dggr_acm_certificate_arn: null
  dggr_acm_certificate_arn_virginia: null
  dggr_hostname: dggr.app
  dggr_zone_id: null
  eks_service_exists: false
  fargate_service_exists: false
  lambda_service_exists: true
  use_dggr_domain: false
