nodeafc8c7:
  cloudfront_service_exists: false
  dggr_acm_certificate_arn: arn:aws:acm:us-east-1:209539466991:certificate/9b56736a-1b97-4ef4-a700-764d0c2a9d96
  dggr_acm_certificate_arn_virginia: arn:aws:acm:us-east-1:209539466991:certificate/9b56736a-1b97-4ef4-a700-764d0c2a9d96
  dggr_hostname: dggr.app
  dggr_zone_id: Z01023802GBWXW1MRJGTO
  eks_service_exists: false
  fargate_service_exists: true
  lambda_service_exists: false
  use_dggr_domain: true
