prod77f0f:
  acm_certificate_arn_virginia: arn:aws:acm:us-east-1:209539466991:certificate/6980249f-075e-4d36-9c5b-3f25276622d9
  cloudfront_service_exists: false
  create_dns_record: false
  dns_zone_id: null
  eks_service_exists: false
  fargate_service_exists: true
  hostname: digger.dev
  lambda_service_exists: false
  lb_ssl_certificate_arn: arn:aws:acm:us-east-1:739940681129:certificate/a0adf19c-75bc-49fe-812c-903e3a2fd6a9
