nodeed82e:
  acm_certificate_arn_virginia: arn:aws:acm:us-east-1:209539466991:certificate/cb409769-be79-4100-94ae-ac182c418d66
  cloudfront_service_exists: false
  create_dns_record: false
  dns_zone_id: null
  eks_service_exists: false
  fargate_service_exists: true
  hostname: dggr.app
  lambda_service_exists: false
  lb_enable_https_redirect: true
  lb_ssl_certificate_arn: arn:aws:acm:us-east-1:209539466991:certificate/cb409769-be79-4100-94ae-ac182c418d66
